# Example for parameters to excecute

# I/O
data_tiled_uri: https://tiled-seg.als.lbl.gov/api/v1/metadata/reconstruction/rec20190524_085542_clay_testZMQ_8bit/20190524_085542_clay_testZMQ_
data_tiled_api_key: <secret>
mask_tiled_uri: https://tiled-seg.als.lbl.gov/api/v1/metadata/reconstruction/seg-partial-rec20190524_085542_clay_testZMQ_8bit/seg-partial-20190524_085542_clay_testZMQ_
mask_tiled_api_key: <secret>
seg_tiled_uri: http://0.0.0.0:8888
seg_tiled_api_key: <secret>

mask_idx: [10, 201, 222, 493]
shift: 2
save_path: results/models
uid: uid0015

model_parameters:
  network: "TUNet"
  num_classes: 3
  num_epochs: 3
  optimizer: "Adam"
  criterion: "CrossEntropyLoss"
  weights: null
  learning_rate: 0.1
  activation: "ReLU"
  normalization: "BatchNorm2d"
  convolution: "Conv2d"

  shuffle_train: True
  batch_size_train: 1
  shuffle_val: True
  batch_size_val: 1
  shuffle_inference: False
  batch_size_inference: 1
  val_pct: 0.2

  depth: 4
  base_channels: 8
  growth_rate: 2
  hidden_rate: 1
